mode: 'standalone'
client:
  name: 'BaseClient'
  client_num: 1
server:
  name: 'BaseServer'
  model: 'Bert'

# 基础配置
base_model: 'Qwen/Qwen2.5-1.5B'
data_path: "client_datasets"
output_dir: 'client_output'
tem_dir: 'TEM'
prompt_template_name: ''

# 联邦学习参数
client_selection_frac: 1.0
num_communication_rounds: 2
num_clients: 3
# num_shared_layers: 15
# restart_from_tem: true

# 本地训练参数
local_batch_size: 64
local_micro_batch_size: 8
local_num_epochs: 10
local_learning_rate: 3.0e-2
local_val_set_size: 0
local_save_steps: 3
cutoff_len: 512

# 大语言模型参数
train_on_inputs: true
group_by_length: false
device_map: 'auto'